USE workshop01_db;

-- 1
(SELECT * FROM 
(SELECT CATEGORY as 계열, DEPARTMENT_NAME as 학과이름, 학생수, (RANK() OVER(ORDER BY 학생수 DESC)) as 순위
FROM TB_DEPARTMENT d inner join (select DEPARTMENT_NO, count(STUDENT_NO) as 학생수 FROM TB_STUDENT group by DEPARTMENT_NO) s
					on d.DEPARTMENT_NO = s.DEPARTMENT_NO
WHERE CATEGORY = '공학'
ORDER BY 학생수 desc) t
WHERE 순위 <= 2)
UNION 
(SELECT * FROM 
(SELECT CATEGORY as 계열, DEPARTMENT_NAME as 학과이름, 학생수, (RANK() OVER(ORDER BY 학생수 DESC)) as 순위
FROM TB_DEPARTMENT d inner join (select DEPARTMENT_NO, count(STUDENT_NO) as 학생수 FROM TB_STUDENT group by DEPARTMENT_NO) s
					on d.DEPARTMENT_NO = s.DEPARTMENT_NO
WHERE CATEGORY = '자연과학'
ORDER BY 학생수 desc) t
WHERE 순위 <= 2)


-- 2

SELECT CLASS_NAME as '과목이름', DEPARTMENT_NAME as '학과이름'
FROM (
	SELECT CLASS_NAME, DEPARTMENT_NAME, CLASS_NO
	FROM (
		SELECT CLASS_NAME, DEPARTMENT_NAME, CLASS_NO
		from (
			select * from TB_CLASS
			WHERE DEPARTMENT_NO IN
								(SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE CATEGORY = '예체능')
		) c
		INNER JOIN TB_DEPARTMENT d
		on c.DEPARTMENT_NO = d.DEPARTMENT_NO
	) t
	WHERE CLASS_NAME LIKE '%논문%'
) TC left OUTER JOIN TB_CLASS_PROFESSOR TCP 
on TC.CLASS_NO = TCP.CLASS_NO
where PROFESSOR_NO is null
ORDER BY 2;


-- 3
SELECT CATEGORY, DEPARTMENT_NAME, 0 as '교수수'
FROM TB_DEPARTMENT TD3  
WHERE DEPARTMENT_NO not IN 
(
	SELECT DEPARTMENT_NO
	from TB_PROFESSOR TP
	WHERE DEPARTMENT_NO in (
		SELECT DEPARTMENT_NO
		FROM TB_DEPARTMENT
		WHERE DEPARTMENT_NO IN (
			select DEPARTMENT_NO
			from TB_DEPARTMENT TD
			where CATEGORY = (
				select CATEGORY
				from TB_DEPARTMENT TD2
				where DEPARTMENT_NAME = '환경조경학과'
			)
		)
	)
	GROUP BY DEPARTMENT_NO
) and CATEGORY = (
		select CATEGORY
		from TB_DEPARTMENT TD2
		where DEPARTMENT_NAME = '환경조경학과'
)
ORDER BY 2 desc;

-- 4
SELECT SUBSTR(TERM_NO, 1, 4) as 년도, ROUND(AVG(`POINT`), 1) as 평점
FROM TB_GRADE
WHERE STUDENT_NO in (
	SELECT STUDENT_NO
	FROM TB_STUDENT
	WHERE COACH_PROFESSOR_NO = (
		SELECT COACH_PROFESSOR_NO
		FROM TB_STUDENT
		WHERE STUDENT_NAME = '서가람'
	) and ENTRANCE_DATE >= '2001-1-1'
)
GROUP BY 년도;

-- 5
SELECT TP2.PROFESSOR_NrAME as '지도교수', st.STCOUNT as '학생 수'
from TB_PROFESSOR TP2
	 inner join (
		SELECT COACH_PROFESSOR_NO, COUNT(STUDENT_NAME) as stcount
		FROM TB_STUDENT
		WHERE COACH_PROFESSOR_NO in (
			SELECT TP.PROFESSOR_NO
			from TB_PROFESSOR TP
				 left join TB_CLASS_PROFESSOR TCP
				 on TP.PROFESSOR_NO = TCP.PROFESSOR_NO
			WHERE TCP.PROFESSOR_NO IS NULL
		)
		GROUP BY COACH_PROFESSOR_NO
	) st
	on TP2.PROFESSOR_NO = st.COACH_PROFESSOR_NO
ORDER BY 1;

-- 6
SELECT d.CATEGORY as '계열', d.DEPARTMENT_NAME as '학과이름', IFNULL(s.stdcnt, 0) as '학생수'
from (
	SELECT CATEGORY, DEPARTMENT_NAME, DEPARTMENT_NO
	FROM TB_DEPARTMENT
	WHERE CATEGORY = '예체능' OR  CATEGORY = '공학'
) d
LEFT JOIN (
	SELECT DEPARTMENT_NO, COUNT(STUDENT_NAME) as stdcnt
	FROM TB_STUDENT
	WHERE DEPARTMENT_NO IN (
		SELECT DEPARTMENT_NO
		FROM TB_DEPARTMENT
		WHERE CATEGORY = '예체능' OR  CATEGORY = '공학'
	)
	GROUP BY DEPARTMENT_NO
) s
ON d.DEPARTMENT_NO = s.DEPARTMENT_NO
ORDER BY 1 asc, 3 desc;

-- 7
SELECT t1.CLASS_NO, t2.CLASS_NAME
FROM (
SELECT CLASS_NO, count(STUDENT_NO) as stdcnt
FROM TB_GRADE
group by CLASS_NO
ORDER BY stdcnt DESC
LIMIT 3
) t1 inner join TB_CLASS t2
  on t1.CLASS_NO = t2.CLASS_NO;