USE WORKSHOP01_DB;

-- 1
(SELECT * FROM 
(SELECT CATEGORY AS 계열, DEPARTMENT_NAME AS 학과이름, 학생수, (RANK() OVER(ORDER BY 학생수 DESC)) AS 순위
FROM TB_DEPARTMENT D INNER JOIN (SELECT DEPARTMENT_NO, COUNT(STUDENT_NO) AS 학생수 FROM TB_STUDENT GROUP BY DEPARTMENT_NO) S
					ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
WHERE CATEGORY = '공학'
ORDER BY 학생수 DESC) T
WHERE 순위 <= 2)
UNION 
(SELECT * FROM 
(SELECT CATEGORY AS 계열, DEPARTMENT_NAME AS 학과이름, 학생수, (RANK() OVER(ORDER BY 학생수 DESC)) AS 순위
FROM TB_DEPARTMENT D INNER JOIN (SELECT DEPARTMENT_NO, COUNT(STUDENT_NO) AS 학생수 FROM TB_STUDENT GROUP BY DEPARTMENT_NO) S
					ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
WHERE CATEGORY = '자연과학'
ORDER BY 학생수 DESC) T
WHERE 순위 <= 2)


-- 2

SELECT CLASS_NAME AS '과목이름', DEPARTMENT_NAME AS '학과이름'
FROM (
	SELECT CLASS_NAME, DEPARTMENT_NAME, CLASS_NO
	FROM (
		SELECT CLASS_NAME, DEPARTMENT_NAME, CLASS_NO
		FROM (
			SELECT * FROM TB_CLASS
			WHERE DEPARTMENT_NO IN
								(SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE CATEGORY = '예체능')
		) C
		INNER JOIN TB_DEPARTMENT D
		ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
	) T
	WHERE CLASS_NAME LIKE '%논문%'
) TC LEFT OUTER JOIN TB_CLASS_PROFESSOR TCP 
ON TC.CLASS_NO = TCP.CLASS_NO
WHERE PROFESSOR_NO IS NULL
ORDER BY 2;


-- 3
SELECT CATEGORY, DEPARTMENT_NAME, 0 AS '교수수'
FROM TB_DEPARTMENT TD3  
WHERE DEPARTMENT_NO NOT IN 
(
	SELECT DEPARTMENT_NO
	FROM TB_PROFESSOR TP
	WHERE DEPARTMENT_NO IN (
		SELECT DEPARTMENT_NO
		FROM TB_DEPARTMENT
		WHERE DEPARTMENT_NO IN (
			SELECT DEPARTMENT_NO
			FROM TB_DEPARTMENT TD
			WHERE CATEGORY = (
				SELECT CATEGORY
				FROM TB_DEPARTMENT TD2
				WHERE DEPARTMENT_NAME = '환경조경학과'
			)
		)
	)
	GROUP BY DEPARTMENT_NO
) AND CATEGORY = (
		SELECT CATEGORY
		FROM TB_DEPARTMENT TD2
		WHERE DEPARTMENT_NAME = '환경조경학과'
)
ORDER BY 2 DESC;

-- 4
SELECT SUBSTR(TERM_NO, 1, 4) AS 년도, ROUND(AVG(`POINT`), 1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO IN (
	SELECT STUDENT_NO
	FROM TB_STUDENT
	WHERE COACH_PROFESSOR_NO = (
		SELECT COACH_PROFESSOR_NO
		FROM TB_STUDENT
		WHERE STUDENT_NAME = '서가람'
	) AND ENTRANCE_DATE >= '2001-1-1'
)
GROUP BY 년도;

-- 5
SELECT TP2.PROFESSOR_NRAME AS '지도교수', ST.STCOUNT AS '학생 수'
FROM TB_PROFESSOR TP2
	 INNER JOIN (
		SELECT COACH_PROFESSOR_NO, COUNT(STUDENT_NAME) AS STCOUNT
		FROM TB_STUDENT
		WHERE COACH_PROFESSOR_NO IN (
			SELECT TP.PROFESSOR_NO
			FROM TB_PROFESSOR TP
				 LEFT JOIN TB_CLASS_PROFESSOR TCP
				 ON TP.PROFESSOR_NO = TCP.PROFESSOR_NO
			WHERE TCP.PROFESSOR_NO IS NULL
		)
		GROUP BY COACH_PROFESSOR_NO
	) ST
	ON TP2.PROFESSOR_NO = ST.COACH_PROFESSOR_NO
ORDER BY 1;

-- 6
SELECT D.CATEGORY AS '계열', D.DEPARTMENT_NAME AS '학과이름', IFNULL(S.STDCNT, 0) AS '학생수'
FROM (
	SELECT CATEGORY, DEPARTMENT_NAME, DEPARTMENT_NO
	FROM TB_DEPARTMENT
	WHERE CATEGORY = '예체능' OR  CATEGORY = '공학'
) D
LEFT JOIN (
	SELECT DEPARTMENT_NO, COUNT(STUDENT_NAME) AS STDCNT
	FROM TB_STUDENT
	WHERE DEPARTMENT_NO IN (
		SELECT DEPARTMENT_NO
		FROM TB_DEPARTMENT
		WHERE CATEGORY = '예체능' OR  CATEGORY = '공학'
	)
	GROUP BY DEPARTMENT_NO
) S
ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
ORDER BY 1 ASC, 3 DESC;

-- 7
SELECT T1.CLASS_NO, T2.CLASS_NAME
FROM (
SELECT CLASS_NO, COUNT(STUDENT_NO) AS STDCNT
FROM TB_GRADE
GROUP BY CLASS_NO
ORDER BY STDCNT DESC
LIMIT 3
) T1 INNER JOIN TB_CLASS T2
  ON T1.CLASS_NO = T2.CLASS_NO;