USE SQLDB2;

-- 1
SELECT JOB AS '직무', TRUNCATE(AVG(SAL), -2) AS '급여 평균'
FROM (SELECT JOB, SAL FROM EMP WHERE DEPTNO = 30) EMPOF30
GROUP BY JOB;

-- 2
SELECT D.DNAME AS '부서명', E.COUNT AS '직원 수'
FROM (SELECT DEPTNO, COUNT(JOB) AS COUNT FROM EMP GROUP BY DEPTNO) E
	INNER JOIN DEPT D
	ON E.DEPTNO = D.DEPTNO
WHERE E.COUNT >= 4;

-- 3
SELECT JOB AS '직무명', FORMAT(SUM(SAL), 0) AS '급여의 합' FROM EMP GROUP BY JOB
UNION
SELECT 'TOTAL', FORMAT(SUM(SAL), 0) FROM EMP
ORDER BY 1;

-- 4
SELECT E.ENAME, E.SAL, S.GRADE
FROM (SELECT ENAME, SAL FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP)) E
INNER JOIN SALGRADE S
ON E.SAL >= S.LOSAL AND E.SAL < S.HISAL;

-- 5
SELECT ENAME AS '직원명', CONCAT(SAL + COMM, '원') AS '급여'
FROM
	(SELECT ENAME, SAL, IFNULL(COMM, 0) AS COMM, HIREDATE FROM EMP) E2
WHERE YEAR(HIREDATE) = 1981
ORDER BY '급여' DESC;

SELECT ENAME AS '직원명', CONCAT(SAL + COMM, '원') AS '급여'
FROM
(SELECT ENAME, SAL, COMM
FROM
	(SELECT ENAME, SAL, IFNULL(COMM, 0) AS COMM, HIREDATE FROM EMP) E2
WHERE YEAR(HIREDATE) = 1981
ORDER BY SAL DESC) E3;

-- 6
-- 6-1
SELECT ENAME AS '직원명', DATE_FORMAT(HIREDATE, "%Y년 %M월 %D일") AS '입사년월일', 'A' AS '그룹'
FROM EMP
WHERE YEAR(HIREDATE) = 1980
UNION
SELECT ENAME, DATE_FORMAT(HIREDATE, "%Y년 %M월 %D일"), 'B'
FROM EMP
WHERE YEAR(HIREDATE) = 1981
UNION
SELECT ENAME, DATE_FORMAT(HIREDATE, "%Y년 %M월 %D일"), 'C'
FROM EMP
WHERE YEAR(HIREDATE) = 1982
UNION
SELECT ENAME, DATE_FORMAT(HIREDATE, "%Y년 %M월 %D일"), 'D'
FROM EMP
WHERE YEAR(HIREDATE) = 1983;

-- 6-2
SELECT ENAME AS '직원명', DATE_FORMAT(HIREDATE, "%Y년 %M월 %D일") AS '입사년월일', CASE 
	WHEN (YEAR(HIREDATE) = 1980) THEN 'A'
	WHEN (YEAR(HIREDATE) = 1981) THEN 'B'
	WHEN (YEAR(HIREDATE) = 1982) THEN 'C'
	WHEN (YEAR(HIREDATE) = 1983) THEN 'D'
END AS '그룹'
FROM EMP;

-- 7
SELECT E1.EMPNO AS'사원 사번', E1.ENAME '사원 이름', E1.MGR AS '관리자 사번', E2.ENAME AS '관리자 이름' 
FROM EMP E1
	INNER JOIN EMP E2
	ON E1.MGR = E2.EMPNO;
	
-- 8
SELECT E.EMPNO, E.ENAME, E.DEPTNO
FROM EMP E
INNER JOIN
(SELECT DEPTNO
FROM DEPT D INNER JOIN LOCATIONS L ON D.LOC_CODE = L.LOC_CODE 
WHERE D.LOC_CODE = (SELECT LOC_CODE FROM LOCATIONS WHERE CITY = 'CHICAGO')) D
ON E.DEPTNO = D.DEPTNO

-- 9
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30);